name: Docs

permissions:
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

on:
  workflow_dispatch:
  push:
    branches: [master]
    tags:
      - "v*"
jobs:
  docs:
    name: build and push static docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["18.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: "Git Fetch & Checkout"
        run: |
          git config --local user.email "team@fluvio.io"
          git config --local user.name "Fluvio Authors"
          git fetch --all
          git checkout -b docs --track origin/docs
          git merge -X theirs origin/master -m "Merge remote-tracking branch 'origin/master' into docs"
      - name: Install Build Dependencies
        run: |
          npm install
      - name: Build docs
        run: |
          make run_docs
          touch docs/.nojekyll
      - name: Commit files
        run: |
          git add --force docs
          git commit -m "Updated Fluvio Node.js client docs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}
